<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common.Messaging.Contracts\Common.Messaging.Contracts.csproj" />
    <ProjectReference Include="..\Common.Security.DataProtection\Common.Security.DataProtection.csproj" />
  </ItemGroup>

</Project>
