<Project Sdk="Microsoft.NET.Sdk">


  <ItemGroup>
    <PackageReference Include="System.IO.Pipelines" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common.FileIngestion.Abstractions\Common.FileIngestion.Abstractions.csproj" />
    <ProjectReference Include="..\Common.FileIngestion.Layouts\Common.FileIngestion.Layouts.csproj" />
  </ItemGroup>

</Project>
